# Generated by Django 5.0.4 on 2024-07-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GiangVien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenGiangVien", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("SoDienThoai", models.CharField(max_length=10)),
                ("DiaChi", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MonHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenMonHoc", models.CharField(max_length=100)),
                ("SoTinhChi", models.IntegerField()),
                ("LoaiMonHoc", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PhongHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TenPhongHoc", models.CharField(max_length=20)),
                ("SucChua", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TietHoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TietTrongKhungGio", models.CharField(max_length=50)),
                ("GioBatDau", models.TimeField()),
                ("GioKetThuc", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="LopHocPhan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SiSo", models.IntegerField()),
                ("NgayBatDau", models.DateField()),
                ("NgayKetThuc", models.DateField()),
                (
                    "giang_vien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TKB_APP.giangvien",
                    ),
                ),
                (
                    "mon_hoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="TKB_APP.monhoc"
                    ),
                ),
                (
                    "phong_hoc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TKB_APP.phonghoc",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThoiKhoaBieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngay_trong_tuan", models.CharField(max_length=10)),
                ("ngay_thuc_te", models.DateField(blank=True, null=True)),
                (
                    "lop_hoc_phan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TKB_APP.lophocphan",
                    ),
                ),
                (
                    "thoi_gian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TKB_APP.tiethoc",
                    ),
                ),
            ],
        ),
    ]
